### ISSUE TITLE
Prepare tutor-contrib-coursegraph for first release

### ISSUE THREAD

**Issue by kdmccormick** [openedx/tutor-contrib-coursegraph#4]
Before being release-able, the repo needs:
* [x] linting and formatting checks
* [x] unit tests
* [x] type checking?
* [x] documentation on settings
* [x] documentation on installation
* [x] distinct `master` and `nightly` branches
* [x] make task for auto merge of master into nightly: #15 
* [x] make task for automated push to PyPI: #14 
* [x] make task to transfer to the openedx org: https://github.com/openedx/tcril-engineering/issues/185
* [x] make task for updated edx-platform documentation: #13

**Comment by kdmccormick** [comment]
Finished, with some follow-ups (see description).
